Feature/movie details screen
K4sho/MTS-Teta pull request #1
Opened 2021-07-10 08:30 UTC by K4sho

2021-07-12 10:46 UTC, NikolayUkhvarov commented on .idea/assetWizardSettings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
убрать файл из индекса

2021-07-12 10:46 UTC, NikolayUkhvarov commented on .idea/libraries/Gradle__com_google_android_material_material_1_4_0_aar.xml
>  <component name="libraryTable">
этот тоже

2021-07-12 10:48 UTC, NikolayUkhvarov requested changes

2021-07-12 10:48 UTC, NikolayUkhvarov commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginTop="224dp"
тут и в других местах нужно вынести в ресурсы все значения (отступы, размеры, цвета)

2021-07-12 10:56 UTC, K4sho commented on .idea/assetWizardSettings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Всю папочку .idea/ лучше убрать?

2021-07-12 10:58 UTC, NikolayUkhvarov commented on .idea/assetWizardSettings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
можно оставить кодстайлы, а так - да

2021-07-12 11:51 UTC, K4sho commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginTop="224dp"
Сделано

2021-07-14 08:16 UTC, NikolayUkhvarov requested changes

2021-07-14 08:16 UTC, NikolayUkhvarov commented on app/src/main/res/drawable/ic_ellipse.xml
> +    android:viewportWidth="41.4"
нужно сделать 40 на 40
(комментарий от лектора)

2021-07-14 08:16 UTC, NikolayUkhvarov commented on app/src/main/res/drawable/ic_home.xml
> +    android:viewportHeight="21">
иконки лучше сделать 18 на 18 обе
(эту и ic_profile)

2021-07-14 08:16 UTC, NikolayUkhvarov commented on app/src/main/res/layout-land/activity_movie_details.xml
> +                android:translationY="-0.15sp"
как появились такие значения?

2021-07-14 08:16 UTC, NikolayUkhvarov commented on app/src/main/res/layout-land/activity_movie_details.xml
> +                android:layout_marginTop="63dp"
нужно спозиционировать элементы относительно друг друга, а не от верхней границы

2021-07-14 08:16 UTC, NikolayUkhvarov commented on app/src/main/res/layout-land/activity_movie_details.xml
> +                android:layout_marginStart="@dimen/age_limit_margin_start"
привязать к правому краю, без левого маржина

2021-07-14 09:00 UTC, K4sho commented on app/src/main/res/drawable/ic_ellipse.xml
> +    android:viewportWidth="41.4"
Только 42, 40 получаются обрезанными

2021-07-16 07:57 UTC, NikolayUkhvarov approved these changes

2021-07-16 08:29 UTC, merged