Feature/database
K4sho/MTS-Teta pull request #10
Opened 2021-08-13 23:30 UTC by K4sho

2021-08-18 14:26 UTC, NikolayUkhvarov requested changes

2021-08-18 14:26 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/ProfileFragment.kt
> +        userNameTextView.text = profileViewModel.getValue(USER_NAME)
может вынести это во вьюмодель, а тут просто подписаться и отобразить по какой-то модели профиля?

2021-08-18 14:26 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/ProfileFragment.kt
> +                profileViewModel.addPairToPrefs(USER_NAME, s.toString())
тоже можно заменить на вызовы типа setName или onUserNameSet

2021-08-18 19:32 UTC, K4sho commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/ProfileFragment.kt
> +                profileViewModel.addPairToPrefs(USER_NAME, s.toString())
сделал

2021-08-18 19:33 UTC, K4sho commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/ProfileFragment.kt
> +        userNameTextView.text = profileViewModel.getValue(USER_NAME)
только EditText сечу единожды в ViewCreated, беря значения из префа. Т.к если это делать в обсервере, то возникает рекурсия. Думал сделать через сабстейт, разбить единый стейт профиля, но решил этого достаточно

2021-08-19 22:30 UTC, NikolayUkhvarov approved these changes

2021-08-23 11:16 UTC, merged