Feature/rv movies list
K4sho/MTS-Teta pull request #2
Opened 2021-07-18 07:39 UTC by K4sho

2021-07-20 08:15 UTC, NikolayUkhvarov requested changes

2021-07-20 08:15 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/data/repository/MoviesModel.kt
> +class MoviesModel(
nit: это ведь репозиторий, а не модель, получается

2021-07-20 08:15 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/MainActivity.kt
> +        categoriesAdapter = CategoriesRecyclerAdapter(callbackForToast)
зачем было разделять с объявлением?

2021-07-20 08:15 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/recycler_views/adapters/CategoriesAdapter.kt
> +        holder.itemView.setOnClickListener { callbackFunction(categories[position].name) }
должно быть в вьюхолдере

2021-07-20 08:15 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/recycler_views/adapters/MoviesAdapter.kt
> +                holder.itemView.setOnClickListener { callbackFunction(movies[position].title) }
тоже вьюхолдер

2021-07-20 08:15 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/recycler_views/adapters/MoviesAdapter.kt
> +const val TYPE_EMPTY = 0
в компаньон

2021-07-20 08:15 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/recycler_views/view_holders/MoviesViewHolder.kt
> +        star1ImageView.setImageResource(if (movie.rateScore > 0) R.drawable.ic_star_selected else R.drawable.ic_star_unselected)
nit: придумай, как сделать это в одну строку (напрмиер, forEachIndexed)

2021-07-20 08:22 UTC, K4sho commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/MainActivity.kt
> +        categoriesAdapter = CategoriesRecyclerAdapter(callbackForToast)
Думал так удобнее. Что бы потом экземпляр этот закинуть в `dispatchUpdatesTo` DiffUtil

2021-07-20 08:23 UTC, K4sho commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/recycler_views/adapters/CategoriesAdapter.kt
> +        holder.itemView.setOnClickListener { callbackFunction(categories[position].name) }
Кликлистенер сетить внутри вьюхолдера?

2021-07-23 14:44 UTC, NikolayUkhvarov approved these changes

2021-07-23 14:46 UTC, merged