add: Добавил swiperefreshlayout и корутину с иммитацией загрузки
K4sho/MTS-Teta pull request #5
Opened 2021-07-28 13:55 UTC by K4sho

2021-08-03 07:55 UTC, NikolayUkhvarov requested changes

2021-08-03 07:55 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/MoviesFragment.kt
> +                delay(400L)
маловато
лучше 2 секунды

2021-08-03 07:55 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/MoviesFragment.kt
> +                delay(400L)
и вынести дилей в модель/репозиторий

2021-08-03 07:55 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/MoviesFragment.kt
> +            } catch (e: CancellationException) {
попробуй через ExceptionHandler

2021-08-03 20:05 UTC, K4sho commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/MoviesFragment.kt
> +                delay(400L)
Испарвил

2021-08-03 20:06 UTC, K4sho commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/MoviesFragment.kt
> +            } catch (e: CancellationException) {
Сделал

2021-08-04 15:57 UTC, NikolayUkhvarov approved these changes

2021-08-04 16:02 UTC, merged