Feature/mvvm and navigation
K4sho/MTS-Teta pull request #7
Opened 2021-08-05 19:41 UTC by K4sho

2021-08-06 17:51 UTC, NikolayUkhvarov requested changes

2021-08-06 17:51 UTC, NikolayUkhvarov commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/MovieDetailsFragment.kt
> +        movie = viewModel.getMoviesById(movieId!!)!!
!! - плохо, а тут два раза плохо

2021-08-06 19:06 UTC, K4sho commented on app/src/main/java/ru/skillbranch/searchmovie/presentation/fragments/MovieDetailsFragment.kt
> +        movie = viewModel.getMoviesById(movieId!!)!!
Исправил

2021-08-07 15:17 UTC, NikolayUkhvarov approved these changes

2021-08-08 07:36 UTC, merged